import React from 'react';
import { Bot, Sparkles, Lightbulb, Zap, CheckCircle2 } from 'lucide-react';

interface Props {
  insight: string;
}

export default function AIInsightCard({ insight }: Props) {
  const isGeminiLive = insight.includes('[Google Gemini AI Analysis]');
  const isHeuristic = insight.includes('[Heuristic AI Analysis]');

  const cleanInsight = insight
    .replace('[Google Gemini AI Analysis]', '')
    .replace('[Heuristic AI Analysis]', '')
    .trim();

  return (
    <div className="glass-panel p-6 rounded-xl border border-blue-500/30 bg-gradient-to-r from-slate-900/90 via-blue-950/20 to-slate-900/90 shadow-xl space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-3 text-blue-400 font-semibold text-base">
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-blue-500/20 border border-blue-500/30">
            <Bot className="w-5 h-5" />
          </div>
          <span>🤖 AI Optimization Insight</span>
        </div>

        {/* Live Provider Badge */}
        {isGeminiLive ? (
          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
            <CheckCircle2 className="w-3.5 h-3.5" />
            <span>Google Gemini AI (Live API)</span>
          </div>
        ) : (
          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-500/10 border border-blue-500/30 text-blue-400 text-xs font-medium">
            <Zap className="w-3.5 h-3.5" />
            <span>Heuristic AI Engine</span>
          </div>
        )}
      </div>

      <div className="text-sm text-slate-300 leading-relaxed font-normal bg-slate-950/40 p-4 rounded-lg border border-slate-800/80 whitespace-pre-line">
        {cleanInsight}
      </div>

      <div className="flex items-center gap-2 text-xs text-slate-400 pt-1">
        <Lightbulb className="w-4 h-4 text-amber-400 shrink-0" />
        <span>
          {isGeminiLive
            ? 'Powered by Google Gemini 1.5/Flash generative reasoning'
            : 'Generated by PackAI heuristic spatial analysis & optimization engine'}
        </span>
      </div>
    </div>
  );
}
